language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
before_script:
    # Prepare pre-accepted licenses to not be promted at installation
    - mkdir -p "$ANDROID_HOME/licenses"
    - echo '' >> "$ANDROID_HOME/licenses/android-googletv-license"
    - echo $LICENSE_TV_1 >> "$ANDROID_HOME/licenses/android-googletv-license"
    - echo '' >> "$ANDROID_HOME/licenses/android-sdk-license"
    - echo $LICENSE_SDK_1 >> "$ANDROID_HOME/licenses/android-sdk-license"
    - echo $LICENSE_SDK_2 >> "$ANDROID_HOME/licenses/android-sdk-license"
    - echo $LICENSE_SDK_3 >> "$ANDROID_HOME/licenses/android-sdk-license"
    - echo '' >> "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - echo $LICENSE_SDK_PREV_1 >> "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - echo '' >> "$ANDROID_HOME/licenses/google-gdk-license"
    - echo $LICENSE_GDK_1 >> "$ANDROID_HOME/licenses/google-gdk-license"
    - echo '' >> "$ANDROID_HOME/licenses/intel-android-extra-license"
    - echo $LICENSE_EXTRA_1 >> "$ANDROID_HOME/licenses/intel-android-extra-license"
    - echo '' >> "$ANDROID_HOME/licenses/mips-android-sysimage-license"
    - echo $LICENSE_SYSIMAGE_1 >> "$ANDROID_HOME/licenses/mips-android-sysimage-license"

script:
    - ./gradlew build check
